# Generated by Django 5.2.6 on 2025-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
