# Generated by Django 5.2.6 on 2025-09-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_exercise_language_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercisehint',
            unique_together={('exercise', 'word_in_exercise', 'language_code')},
        ),
    ]
